name: Electron CD
on: [push]
env:
  GIT_TAG: ${{ github.ref_name }}
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build GetAppIcon
        run: |
          cd GetAppIcon      
          make build
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: npm install
        run: |
          npm install
      - name: Publish
        run: |
          npm run pack --appVersion ${{ env.GIT_TAG }} --archive
      - name: Cleanup artifacts
        run: |
          npx rimraf "build/!*.zip"
      #      - name: Upload artifacts
      #        uses: actions/upload-artifact@v4
      #        with:
      #          path: build
      - run: |
          ls -l build
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "build/*.zip"
