name: Electron CD
on: [push]
env:
  GIT_TAG: ${{ github.ref_name }}
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build GetAppIcon
        run: |
          cd GetAppIcon      
          make build

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: npm install
        run: |
          npm install

      - name: Publish
        run: |
          npm run pack -- --appVersion ${{ env.GIT_TAG }}

      - run: |
          ls -l build

      - name: Archive
        run: |
          zip -r "build/Hyper Launcher-darwin-arm64.zip" "build/Hyper Launcher-darwin-arm64"
          zip -r "build/Hyper Launcher-darwin-x64.zip" "build/Hyper Launcher-darwin-x64"

      - name: Cleanup artifacts
        run: |
          find build -mindepth 1 ! -name "*.zip" -exec rm -rf {} +

      - run: |
          ls -l build

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "build/*.zip"
